apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "matomo.fullname" . }}-tls-ingress
  labels:
{{ include "matomo.labels" . | indent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.matomo.ingress.hostname }}`)
      kind: Rule
      priority: 10
      services:
        - name: {{ template "matomo.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    secretName: matomo-elzokalobar

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "matomo.fullname" . }}-ingress
  labels:
{{ include "matomo.labels" . | indent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.matomo.ingress.hostname}}`)
      kind: Rule
      priority: 10
      services:
        - name: {{ template "matomo.fullname" . }}
          port: {{ .Values.service.port }}